### ISSUE TITLE
Issue when moving poe sniper to another window

### ISSUE THREAD

**Issue by P4uLT** [licoffe/POE-sniper#19]
Hi,
Currently have a issue when i move my poe sniper to my secondary screen. Works great until i restart the tool.

Error :
![poesniper](https://user-images.githubusercontent.com/7680607/28880492-7cd49590-77a5-11e7-986d-b1889f8eddc7.PNG)

Json content :

`{"sound":"sound2.mp3","volume":0.5,"message":"@<account> Hi, I would like to buy your <item> listed for <price> in <league> (stash tab \"<stashTab>\"; position: left <left>, top <top>)","barter":"@<account> Hi, I would like to buy your <item> in <league> (stash tab \"<stashTab>\"; position: left <left>, top <top>)","RATES_REFRESH_INTERVAL":10000,"POE_TRADE_STATS_INTERVAL":3600000,"CHUNK_RETRY_INTERVAL":1000,"CHUNK_DOWNLOAD_INTERVAL":750,"STREAM_TOP_WAIT_INTERVAL":2000,"SCROLL_BACK_TOP_SPEED":500,"NOTIFICATION_QUEUE_INTERVAL":5000,"writeChunkStats":false,"globalClipboard":false,"leagues":["Standard","Hardcore","Legacy","Hardcore Legacy","2 Week Turmoil (JRE094)","2 Week Turmoil HC (JRE095)"],"defaultLeagueIndex":2,"showStatusBar":false,"windowWidth":1296,"windowHeight":1000,"x":1912,"y":-8,"useBeta":false,"checkUnderpriced":false}}`

After investigation : one " } " is duplicated at the end of the json.

**Comment by Chromist** [comment]
I am glad you posted this, I ran into the exact same issue.  I have zero knowledge when it comes to resolving issues as these so this was very helpful.

**Comment by licoffe** [comment]
Hi guys, sorry for the delayed answer. Been away from my computer since the last release. This issue happens when several versions of the program are running simultaneously. Each time the window is moved, the new position gets recorded to config.json. When several versions of the program are running at the same time, they all record the new position to config.json which ends up corrupting the config file. I prevent two identical versions of the program to run at the same time, however it's possible that two different versions might be able to run simultaneously. To solve the issue for now you can either fix the config.json file by hand or remove it and it will be recreated by the program on launch.

**Comment by licoffe** [comment]
I'm disabling the save window position/size feature for now.
