### ISSUE TITLE
Feature Request - Turn off poe.trade stats

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#24]
Hi Licoffe,

I would be interested in the ability to turn off the poe.trade stats (either locally or globally).  Generally speaking I have not used that feature and I am wondering if it might slow down the processing of the app (or cause timeouts) when I am attempting to run a large number of filters.

Obviously you know the program better than I do.  It is possible that this function is so lightweight that it is adding little to no strain.  If that Is the case then I'll trust your judgement and you can ignore this feature request.

Thanks,
Gdneye

**Comment by licoffe** [comment]
Hi gdneye,

> I would be interested in the ability to turn off the poe.trade stats (either locally or globally)

I will add this feature in the options. It shouldn't slow down the processing since the stats are only fetched when adding a new filter or automatically every hours. When it does, the program may slow down a bit for a few seconds. However, it may clutter the screen, so giving users the possibility to disable it would probably be helpful.

**Comment by gdneye** [comment]
Thanks, and thanks for letting me know how it works so I know it isn't slowing things down.
