### ISSUE TITLE
Please add option for filtering by exact currency price.

### ISSUE THREAD

**Issue by cognitive-rift** [licoffe/POE-sniper#27]
I would like to trade certain items in only certain currencies. Please add more currencies and the possibility to only look at offers in that currency.

**Comment by Newbrict** [comment]
My suggestion for implementing this feature is to add a min price alongside the existing max price option

this way ( unless on the very small chance that the two currency items have the exact same value ) you can imply this feature

**Comment by licoffe** [comment]
> My suggestion for implementing this feature is to add a min price alongside the existing max price option

Not sure I understand. This way you would be able to filter prices included in the [min;max] interval but it wouldn't restrict prices to a specific currency.

**Comment by Newbrict** [comment]
Yeah but what are the odds two currencies will trade 1:1 on poe trade :p

**Comment by licoffe** [comment]
As far as I understand here it's not so much about the price as it is about the currency type :) What I'm doing right now is that I'm converting every prices in various currencies from the API to chaos using the poe-rates backend. The requested feature is actually more "naive" than the current approach since it would not have to do conversions, but that's true that it could be useful :)

**Comment by Newbrict** [comment]
do u have steam? add me ? same nick as on github for me

**Comment by licoffe** [comment]
Sorry don't have a steam, what about Discord? I'll be gone for the next 4 days anyways. We can talk on the 22nd if possible.

**Comment by licoffe** [comment]
So, I implemented this feature, it's gonna appear in the next release.

**Comment by licoffe** [comment]
Closing this since the feature has been implemented
