### ISSUE TITLE
being notified for one item each iteration 

### ISSUE THREAD

**Issue by Xloctis** [licoffe/POE-sniper#4]
as title says notification for 1 filter pops each new update of stash ID's

**Comment by licoffe** [comment]
For each item which matches the filters I'm sending a notification. The code is checking about 1000 items/second. I'm not sure what you mean exactly.

**Comment by Xloctis** [comment]
i mean someone listed doctor for 720 vaals which is great deal, and im getting notfication that he listed it each second for as long as program is up

**Comment by gdneye** [comment]
Hey Xloctis,

Since this app is just listening to the API stream and not storing any data it will send an update every time that given stash tab is updated.  Websites like poe.trade use an indexer (i.e. they store results in a database and query against those results.)  They only update when they see an important change in the specific item you are looking for.  Generally an important change is just new item, removal of item, or price change.  

Since licoffe's program is not storing old data it has no way of knowing if that data is new, so it will ping you every time it receives the data.  Unfortunately GGG built the API so that any time any change is made to any part of a stash tab, it re-sends the entire stash tab.  So if the guy was organizing that stash tab (or adding to it or whatever), you will continue to get notifications.

Its only really a problem with price fixers.  Normal people will either sell you the item for the low price, or  will realize their mistake and reprice the item.  Either way it will be removed pretty quickly.

The reason you do it this way is efficiency.  It takes (a bit of) extra time and a lot of storage to track all of the items.

**Comment by licoffe** [comment]
So what I did for now is to prevent visual and audio notifications as well as copy to clipboard when the item is already in the list. I keep track of the unique ids of each items added to the result list.
