### ISSUE TITLE
[Feature request - UI] Textbox for Item Type

### ISSUE THREAD

**Issue by xkomachi** [licoffe/POE-sniper#45]
1. Open a new filter.
2. Click on the type selectbox.
3. Type something with the keyboard and press enter. 
Current behavior: The correct type is selected.
Requested behavior: The scrollist starts from under the type selection box, what you type shows up in the selection box, and the list adapts and only shows matching terms (similar to the affix selection).

**Comment by licoffe** [comment]
Changed in the last commit

**Comment by xkomachi** [comment]
Fixed in the latest update. However, the 'item type' handles smaller resolutions extremely poorly. 

Apologies for the whacky editing, the following video demonstrates the issue:
https://files.catbox.moe/aztmdp.mp4

Related: https://github.com/licoffe/POE-sniper/issues/49

**Comment by licoffe** [comment]
> However, the 'item type' handles smaller resolutions extremely poorly.

In this case, it's not just the item type, but the whole UI :D I didn't plan on making it responsive from the beginning since it's ment to be used on desktop computers. It's only resizable to a certain extent. If it's really required, and we need some tablet/mobile layout, it can easily be done using the grids from Materialize (http://materializecss.com/grid.html).
