### ISSUE TITLE
[Issue] Sometimes unable to add new filters.

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#5]
I haven't found a definitive pattern yet, but sometimes I become unable to add new filters.  I have noticed that it is more likely to occur after the app has ran for a while.

https://youtu.be/hWipcYQ-U3Q

**Comment by licoffe** [comment]
After playing around, this seems to happen after removing a filter. I'm looking into it.

**Comment by licoffe** [comment]
Somehow this bug is due to not being able to fetch the currently selected league in the interface.

**Comment by licoffe** [comment]
Found it! It was due to the "Clear Filter/Cancel" button not resetting the league correctly. The value was set to null which prevented the addFilter functions to pull the currency rates and add the filter. It will be fixed in the next commit/release. I'll let you close the issue to double-check that it's solved.

**Comment by gdneye** [comment]
Nice!  Glad you were able to find that.

**Comment by licoffe** [comment]
Just published a new release. Could you try it to see if it fixes your issue?

**Comment by gdneye** [comment]
Will do, been busy this weekend but I'll test it out tonight or tomorrow.

**Comment by gdneye** [comment]
After testing lightly during regular gameplay I have not been able to replicate this bug with the new release.  I'm guessing its fixed and will open a new Issue with an explanation if I run into any further problems.
