### ISSUE TITLE
Issues adding new affixes

### ISSUE THREAD

**Issue by gdneye** [licoffe/POE-sniper#58]
2 Issues

1 - When attempting to add an affix manually the text box covers the "add" button.  On larger screens it is just barely visible.
2 - Once I actually click the "Add" button the program goes all white and appears to crash.

I'm trying a new thing with providing the video.  I compressed it with winzip and added it.  Hopefully that works.  If not I'll throw it on youtube again.

[2017-09-13 17-37-18.zip](https://github.com/licoffe/POE-sniper/files/1301172/2017-09-13.17-37-18.zip)

**Comment by licoffe** [comment]
Thanks for the video, it works indeed! 

I was able to reproduce the issue. An exception is raised and not caught, crashing the program. The issue was that the program could not extract the type of mod added (explicit, implicit, etc...). I patched it, but until I provide the next release, you will have to provide the mod type like this:
`(explicit) # reduced charges` instead of `# reduced charges`.

**Comment by gdneye** [comment]
Ahh that makes sense.  I only noticed it after the latest release.  Thanks again.

**Comment by licoffe** [comment]
By the way, you can press "ESC" to close the completion menu :)
