### ISSUE TITLE
Price filter not working, and old items keep popping up

### ISSUE THREAD

**Issue by chinhodado** [licoffe/POE-sniper#76]
Just now the app has been behaving weirdly. The price filter is not working at all, and items listed before the app were run keeps popping up.

**Comment by licoffe** [comment]
> The price filter is not working at all

So you mean if you set a price limit at 1 chaos, it shows items with a price above the limit? That could be an issue with the poe-rates backend which I use to do currency price conversion.

> items listed before the app were run keeps popping up

What do you mean by that?

**Comment by chinhodado** [comment]
With the price filter, for example, I have some items set at 1 ex max price, but items with 2 ex, 5 ex, etc. price keep popping up. As if the price filter has no effect. And this is even without any price conversion (price filter was made in ex, price posted was also in ex)

With the second issue, what happened was that every time I started sniping, the change ID reset to a (fixed?) old number, so all items after that change ID showed up.

**Comment by licoffe** [comment]
> With the second issue, what happened was that every time I started sniping, the change ID reset to a (fixed?) old number, so all items after that change ID showed up.

I check both poe-rates and poe.ninja to fetch the last change ID. It looks like poe.ninja changed the field name from its API so it returned nothing and poe-rates was stuck on the same change id since this morning.

Could you post a screenshot of the non-working filter?

**Comment by chinhodado** [comment]
The change id issue seems to have been resolved. But the price filter issue still seems to be there. For example, here is a filter for added attack Vinktars max 150c:

![image](https://user-images.githubusercontent.com/1388219/33241253-e43b6024-d290-11e7-888e-b3cea1668acb.png)

I am still seeing listings for 200c, 270c, etc. popping up.

**Comment by licoffe** [comment]
Thanks for the screenshot! I'm trying to reproduce the issue on my side with the same filter settings.

I was wondering if this could be due to another filter setting, for example a unique flask filter without price restrictions. A quick way to check this is to click on the icon I circled in the picture bellow on your vinktar filter: it will remove all the entries found by that filter. If the listings with a price above 150c are removed, it means that they've been tagged by the vinktar filter and there's a bug on my side.

![vinktar](https://user-images.githubusercontent.com/17992001/33254553-871eb90e-d349-11e7-8ee8-b553cb113283.png)

**Comment by chinhodado** [comment]
This seems to not happen anymore. I will close the issue.
