### ISSUE TITLE
[Request] Is it possible to add a note-taking field to your app for each item?

### ISSUE THREAD

**Issue by TA2DF** [licoffe/POE-sniper#90]
I think the title text is quite descriptive.

I already thank you so much for all your efforts and your work so far.

**Comment by licoffe** [comment]
Would this go on the filter level?

![mockup](https://user-images.githubusercontent.com/17992001/34816097-23ec281a-f6b4-11e7-9b96-f2ccc9871731.png)

**Comment by licoffe** [comment]
I implemented this feature in the [online version](http://poe-rates.com/live) of the tool.

**Comment by TA2DF** [comment]
Unfortunately I don't using online version!.. Will you also add that feature to your offline version?

**Comment by licoffe** [comment]
The online version is actually more up to date with the latest content (affixes, unique items, etc.) and I’m thinking about deprecating poe-sniper to be honest. The reason is that the online version is a solution to the issue (unlimited connection plan, large bandwidth, third party tool to download, ...) preventing everyone from using the tool and it’s hard for me to maintain two code bases as a single individual. Now, I can’t really close the poe-sniper codebase because a lot of people are currently using it, but I’m actually really interested to know why you would stick to Poe-sniper over the online version. Is it feature related?

**Comment by TA2DF** [comment]
It is related of storability and portability of personal data where stored in folder of "AppData"... Along with that, especially, privacy related!

**Comment by licoffe** [comment]
Concerning storage, in the online version of the tool, the filters are stored in the local storage as a string variable. It’s true, that’s it’s not convenient to export or import but I could easily implement a solution to simplify the process.

Concerning privacy, with the online version, users need to send filter information so that they can receive matching items since the filtering is done on my server. However and you have to trust me on that (but you already kind of do since you’re using my tool), filters are not written to disk on the server, only stored in memory in a tree-like structure which is very obnoxious to read from (I know since I had to debug the filter algorithm).

**Comment by TA2DF** [comment]
Thank you very much for your kindly and detailed descriptions...

Despite everything, I don't want my personal informations to be stored in environments of can't be controlled by me.

I wish you success in your continuing work.
